Homework 4. Task 2. Dubrovchenko Mark
Mmorgenn/spbu_python_first_course pull request #17
Opened 2023-10-25 19:48 UTC by Mmorgenn

2023-11-14 21:49 UTC, Arsene-Baitenov requested changes
0.005 представляется так же как 0.5
Если передать 4.0 будет вывод +0.1000*2^3 не значащих нулей быть не должно

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +    num_input = input("Ввещите вещественное число: ")
Ввещите от слова вещественное?

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +        start()
А как остановиться вводить числа?

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +        raise ValueError("It should not be inf")
Стоило использовать math.isnan, math.isfloat, math.isinf

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +        print("Ошибка! От вас требовалось написать число от 1 до 3")
Что за принуждение? Поэтому там while True написан?

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +    )
```suggestion
    int_bin = get_binary_integer(int(int_part))
    float_bin = get_binary_fraction(int(float_part), precision)
```

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +    )
Смысл так писать? в данном случае это лишь понизит читаемость

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +    )
0.005 представляется так же как 0.5 из-за конвертация дробной части в int

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +        num = num % 1
```suggestion
        num = num % 1
        if num == 0:
            return bin_num
```

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +        bin_num.append(str(num // 1)[0])
Зачем индексация по 0, это та же самая строка

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +        element = int_part.pop(-1)
```suggestion
        element = int_part.pop()
```

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +    result = "0." + ("").join(float_part)
```suggestion
    result = "0." + "".join(float_part)
```

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +def normalization(int_part, float_part):
нормализация чего?

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +        return ["0"]
Если передать 4.0 будет вывод +0.1000*2^3 не значащих нулей быть не должно

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +def fp_conversation(num_list, range, precision):
О чём разговаривают?

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +def fp_conversation(num_list, range, precision):
Первый элемент `num_list` это строка знака, название не соответствует содержанию

2023-11-14 21:49 UTC, Arsene-Baitenov commented on src/homework/Homework_4/hw2.py
> +        mantissa += "0" * (precision - len(mantissa))
Вообще ничего не понимаю

2023-11-30 15:47 UTC, toadharvard approved these changes

2023-11-30 15:47 UTC, merged