Homework 4. Task 3. Dubrovchenko Mark
Mmorgenn/spbu_python_first_course pull request #18
Opened 2023-10-26 14:17 UTC by Mmorgenn

2023-10-29 21:33 UTC, toadharvard requested changes

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3.py
> +    size: 0
```shell

$ mypy .
  hw3.py:6: error: Invalid type: try using Literal[0] instead?  [valid-type]
```

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3.py
> +    size: 0
Ну ты буквально указал, что тип размера очереди ноль. Я не понимаю как тебе IDE это разрешила сделать. Или ты из VSCode'a без плагинов?

Аналогично указанные ниже типы полный кринж

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3.py
> +    tail: None
head: Node | None

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3.py
> +def size(queue):
get_

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3.py
> +def empty(queue):
is_

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3.py
> +def top(queue):
get_

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3.py
> +def top(queue):
view_

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3_1.py
> +from hw3 import create, size, top, push, pop
из-за кринжовых названий папок теперь нельзя сделать полный импорт вида: `from src.homework3.queue import is_top`

Время переименовывать все

2023-10-29 21:33 UTC, toadharvard commented on src/homework/Homework 25.10.23/hw3_1.py
> +def get_top(queue):
не уверен, что эти две функции имеют какой-то смысл, но как знаешь

2023-10-29 23:31 UTC, toadharvard requested changes

2023-10-29 23:31 UTC, toadharvard commented on src/homework/Homework_4/hw3.py
> +    value: None
Бро... Ну что ты делаешь

2023-10-29 23:31 UTC, toadharvard commented on src/homework/Homework_4/hw3.py
> +    tail: None
Ну ты шутишь

2023-10-29 23:31 UTC, toadharvard commented on src/homework/Homework_4/hw3.py
> +    value: None
Типы так не работают. Прочитай документацию или хотя бы посмотри видео на ютубе...

2023-10-29 23:31 UTC, toadharvard commented on src/homework/Homework_4/hw3.py
> +    value: None
value произвольный тип, а не ТОЛЬКО None
next -- типа Node
`from __future__ import annotations`

2023-11-08 18:06 UTC, toadharvard approved these changes

2023-11-11 17:52 UTC, toadharvard approved these changes

2023-11-30 09:25 UTC, SpirinEgor approved these changes

2023-11-30 09:25 UTC, SpirinEgor commented on src/homework/Homework_4/hw3.py
> +from __future__ import annotations
А это зачем?

2023-11-30 09:30 UTC, merged