Homework 6. Task 1. Dubrovchenko
Mmorgenn/spbu_python_first_course pull request #25
Opened 2023-11-22 23:16 UTC by Mmorgenn

2023-12-21 14:50 UTC, SpirinEgor requested changes
Кажется тесты надо пересмотреть:
1. Сейчас в целом сложно проверить корректность, большая куча кода со сложной структурой
2. Логика построения может меняться => деревья тоже. АВЛ деревья неоднозначны, они лишь определяют инвариант на разницу высот
3. Надо проверять именно поддержание баланса, то есть, например, добавить 1000 случайных значений и после каждого проверить, что дерево верно сбалансированно

2023-12-21 14:50 UTC, SpirinEgor commented on src/homework/Homework_6/Homework_6_1/shopping.py
> +FILE_OUTPUT_BALANCE = "output_balance.txt"
Давай не хардкодить, пусть пути передаются аргументами при запуске. Можно значения по умолчанию задать для удобства. Тут `argparse` модуль поможет

2023-12-21 14:50 UTC, SpirinEgor commented on src/homework/Homework_6/avl_tree.py
> +    height: int = 0
Кажется дерево из 1 вершины имеет высоту 1, а не 0. Логичнее рассуждать будет, тогда и для None надо будет не костыльный -1 возвращать, а 0 -- нет дерева => на нулевой высоте

2023-12-21 14:50 UTC, SpirinEgor commented on src/homework/Homework_6/avl_tree.py
> +        return _hash_key(node.right, key)
Вот это надо бы вынести в отдельную функцию и переиспользовать по возможности, например, в `get_value`

2023-12-21 14:50 UTC, SpirinEgor commented on src/homework/Homework_6/avl_tree.py
> +        return _get_maximum_key(node.right)
Давай циклом, чтобы не засорять стек вызовов функций

2023-12-21 14:50 UTC, SpirinEgor commented on src/homework/Homework_6/avl_tree.py
> +def get_higher_bound(tree_map: TreeMap[Value], key: Key) -> Key:
`upper_bound`

2023-12-21 14:50 UTC, SpirinEgor commented on src/homework/Homework_6/avl_tree.py
> +    def _get_lower_bound(node: TreeNode[Value], key: Key, min_key):
Копипаста?)

2023-12-21 14:50 UTC, SpirinEgor commented on src/homework/Homework_6/avl_tree.py
> +    new_node.size = _get_size(new_node.right) + _get_size(node) + 1
У тебя же есть функции для апдейта высот и размеров

2023-12-21 14:50 UTC, SpirinEgor commented on tests/homeworks/Homework_6/test_avl_1.py
> +def test_put(tree_elements, element, expected):
Очень страшный инпут у функции, даже толком не проверить насколько верные деревья выше...

2023-12-21 21:18 UTC, Mmorgenn commented on src/homework/Homework_6/avl_tree.py
> +    height: int = 0
-1 для None было в презентации)

2023-12-27 14:10 UTC, SpirinEgor approved these changes

2023-12-27 14:10 UTC, SpirinEgor commented on tests/homeworks/Homework_6/test_avl_1.py
> +        put(dummy_tree, i, i)
Лучше рандомить все же

2023-12-27 14:10 UTC, merged