Practice 9. Dubrovchenko Mark
Mmorgenn/spbu_python_first_course pull request #29
Opened 2023-12-08 19:38 UTC by Mmorgenn

2023-12-11 18:36 UTC, SpirinEgor requested changes
Надо исправить баги в реализации
Тесты довольно странные, они проверяют не функциональность, а разные автоматы, хотя эти автоматы пользователю недоступны

2023-12-11 18:36 UTC, SpirinEgor commented on src/practice/Pr_9/fsm.py
> +    transfers: dict[str:int]
🥴

2023-12-11 18:36 UTC, SpirinEgor commented on src/practice/Pr_9/fsm.py
> +    alphabet: list[str],
Алфавит лучше по переходам создавать, чтобы упростить создание

2023-12-11 18:36 UTC, SpirinEgor commented on src/practice/Pr_9/fsm.py
> +    if symbol in fsm.alphabet:
Инвертируй if!

2023-12-11 18:36 UTC, SpirinEgor commented on src/practice/Pr_9/fsm.py
> +        if symbol in current_transfers.keys():
а если не в ключах? Получается неправильно работает -- когда нет перехода, то не завершается с ошибкой, а переходит к следующему символу

2023-12-11 18:36 UTC, SpirinEgor commented on src/practice/Pr_9/fsm.py
> +            fsm.current_state = current_transfers[symbol]
Получается ДКА нельзя 2 раза использовать -- теряется информация о стартовом состоянии. Вообще текущее не надо держать внутри ДКА, это не относится к его структуре

2023-12-11 18:36 UTC, SpirinEgor commented on tests/practice/Pr_9/test_fsm_realisation.py
> +first_dummy_fsm = create_fs_machine(
Глобальный код :( Для таких тестовых объектов надо https://docs.pytest.org/en/6.2.x/fixture.html

2023-12-19 19:35 UTC, Mmorgenn commented on src/practice/Pr_9/fsm.py
> +            fsm.current_state = current_transfers[symbol]
Так ведь validate_string запоминает начальное состояние и возвращает его в ДКА при получении результата. Таким образом получится использовать ДКА несколько раз

2023-12-19 19:41 UTC, Mmorgenn commented on src/practice/Pr_9/fsm.py
> +        if symbol in current_transfers.keys():
Если не в ключах или не в алфавите, то шаг завершится False. Функция validate_string в случаи если шаг завершился False вернет False (т.е цикл вызовов шагов прекратится). Но я перепишу функцию move чуть красивее

2023-12-21 15:01 UTC, SpirinEgor requested changes
Все хорошо, кроме странного изменения текущего состояния. Перепиши только эту функцию, чтобы более органично двигаться по ДКА

2023-12-21 15:01 UTC, SpirinEgor commented on src/practice/Pr_9/fsm.py
> +    zero_state = fsm.current_state
Зачем такие костыли, вместо запоминания стартового состояния и его изменения прямо в ДКА просто храни текущее состояние в отдельной переменной и его обновляй...

2023-12-23 20:08 UTC, SpirinEgor approved these changes

2023-12-23 20:08 UTC, merged